### ISSUE TITLE
Ajustar contraste no site 

### ISSUE THREAD

**Issue by iagocavalcante** [iagocavalcante/qtube#16]
As cores ficaram muito agressivas com a nova logo, verificar uma cor que fique agradável

**Comment by mandyellow** [comment]
@iagocavalcante fiz uma sugestão, tentei mudar pouca coisa para ficar fácil de alterar. Segue abaixo.

![web 1920 1](https://user-images.githubusercontent.com/30158643/46511652-30552900-c826-11e8-8f9c-cded7617b3e0.png)

**Comment by iagocavalcante** [comment]
Caralho que trabalho bom demais <3 vou deixar aberto a issue até a gente fazer a alteração no site, obrigadão de novo @mandyellow
