### ISSUE TITLE
Criação de página de download

### ISSUE THREAD

**Issue by iagocavalcante** [iagocavalcante/qtube#4]
Criação de página simples para a realização do download da aplicação, a página será servida pelo github.io

**Comment by MarcosSarges** [comment]
Posso fazer isso, mas atualizar o readme para realizar o build Dev e Prod do projeto

**Comment by iagocavalcante** [comment]
Beleza, então vou criar outra issue pro README, pode ser ?

**Comment by MarcosSarges** [comment]
tira uma dúvida? só pode ter uma página github.io ou não?

**Comment by iagocavalcante** [comment]
Sim, nesse caso irá ficar hein iagocavalcante.github.io/qtube

**Comment by MarcosSarges** [comment]
então eu vou fazer o fork e o pr vai para lá

**Comment by iagocavalcante** [comment]
Acho que pode ser em uma branch e eu habilito aqui para pegar dessa branch.

**Comment by MarcosSarges** [comment]
olha como esta o site https://marcossarges.github.io/qtube/

**Comment by iagocavalcante** [comment]
Gostei bastante, provavelmente vamos ter mais issues por conta da logo, consequentemente vamos mudar o tema da aplicação. To esperando outro PR da Logo e colocarei em votação pra gente escolher. 

Parabéns @MarcosSarges ficou daora

**Comment by MarcosSarges** [comment]
Obrigado *-* 

Realmente vai ter outros issuses na questão da logo e da versão para mac

**Comment by MarcosSarges** [comment]
só altera uma coisa, o nome do arquivo licence para license... infelizmente passou despercebido quando fiz o pr
